;; -*- mode : lisp -*-
(source gnu)
(source melpa)
(source marmalade)

(depends-on "bind-key")
(depends-on "cask")
(depends-on "dash")
(depends-on "drag-stuff")
(depends-on "exec-path-from-shell")
(depends-on "expand-region")
(depends-on "f")
(depends-on "flycheck")
(depends-on "flycheck-cask")
(depends-on "htmlize")
(depends-on "idle-highlight-mode")
(depends-on "magit")
(depends-on "multiple-cursors")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "popwin")
(depends-on "prodigy")
(depends-on "projectile")
(depends-on "s")
(depends-on "smartparens")
(depends-on "smex")
(depends-on "use-package")
(depends-on "web-mode")
(depends-on "yasnippet")
(depends-on "linum-relative")
(depends-on "smooth-scroll")
(depends-on "browse-kill-ring")
(depends-on "color-theme")

(depends-on "helm")
(depends-on "helm-git-grep")
(depends-on "helm-ls-git")
(depends-on "helm-themes")
(depends-on "helm-gtags")
(depends-on "helm-pydoc")
(depends-on "helm-go-package")

(depends-on "git-gutter")
(depends-on "rainbow-delimiters")
(depends-on "powerline")
(depends-on "elscreen")
(depends-on "auto-complete")

(depends-on "go-mode")
(depends-on "go-autocomplete")
(depends-on "go-eldoc")
(depends-on "go-direx")
(depends-on "go-errcheck")
(depends-on "haskell-mode")
(depends-on "ruby-mode")
(depends-on "pylint")
(depends-on "yaml-mode")
(depends-on "json-mode")
